name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Profile overview
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: arvemy
          filename: github-metrics.svg
          config_timezone: Europe/Istanbul
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: arvemy
          filename: metrics.languages.svg
          config_timezone: Europe/Istanbul
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: "0%"
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

      - name: Isometric calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: arvemy
          filename: metrics.isocalendar.svg
          config_timezone: Europe/Istanbul
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
